seleniumGrid=false
gridURL=http://localhost:4444/wd/hub
browser=chrome
#Application URL
url = https://v0-lead-manager-app.vercel.app/login

#credentials
username = admin@company.com
password = Admin@123
implicitWait = 10
explicitWait = 30